from pyray import * # type: ignore
import pyray
from pytmx import * # type: ignore
from typing import * # type: ignore 
from math import * # type: ignore
import sys, os, json
from os.path import join
from dataclasses import dataclass
from functools import wraps
from time import perf_counter

# keys
from raylib import  KEY_A, KEY_D, KEY_S, KEY_W, KEY_Q, KEY_E, KEY_R, KEY_T, KEY_Z, KEY_U, KEY_I, KEY_O, KEY_P, KEY_F, KEY_G, KEY_H, KEY_J, KEY_K, KEY_L, KEY_Y, KEY_X, KEY_C, KEY_V, KEY_B, KEY_N, KEY_M, KEY_LEFT_SHIFT, KEY_RIGHT_SHIFT, KEY_BACK, KEY_ENTER, KEY_SPACE, KEY_ESCAPE, KEY_TAB, KEY_F11
# buttons
from raylib import GAMEPAD_AXIS_LEFT_X, GAMEPAD_AXIS_LEFT_Y, GAMEPAD_AXIS_RIGHT_X, GAMEPAD_AXIS_RIGHT_Y, GAMEPAD_BUTTON_LEFT_FACE_DOWN, GAMEPAD_BUTTON_LEFT_FACE_LEFT, GAMEPAD_BUTTON_LEFT_FACE_RIGHT, GAMEPAD_BUTTON_LEFT_FACE_UP, GAMEPAD_BUTTON_MIDDLE_RIGHT, GAMEPAD_BUTTON_MIDDLE_LEFT, GAMEPAD_BUTTON_MIDDLE, GAMEPAD_BUTTON_LEFT_TRIGGER_1, GAMEPAD_BUTTON_LEFT_TRIGGER_2, GAMEPAD_BUTTON_RIGHT_TRIGGER_1, GAMEPAD_BUTTON_RIGHT_TRIGGER_2, GAMEPAD_BUTTON_RIGHT_FACE_DOWN, GAMEPAD_BUTTON_RIGHT_FACE_UP, GAMEPAD_BUTTON_RIGHT_FACE_LEFT, GAMEPAD_BUTTON_RIGHT_FACE_RIGHT

if TYPE_CHECKING: from main import Game
